// Generates src/styles/Icons.css: mono colour icons (GitHub Octicons) that
// replace Codebase's icon font and image icons. Run with `npm run icons`
// after changing the mapping below.
import { readFileSync, writeFileSync } from 'fs';

const svg = (name) => {
    const file = `node_modules/@primer/octicons/build/svg/${name}-16.svg`;
    const data = readFileSync(file, 'utf-8').trim().replace('<svg ', '<svg fill="black" ');
    return `url("data:image/svg+xml,${encodeURIComponent(data).replace(/'/g, '%27')}")`;
};

// The same icon as a plain image in a fixed colour, for places where the icon
// sits inside a box and so can't be a mask.
const svgColor = (name, color) => {
    const file = `node_modules/@primer/octicons/build/svg/${name}-16.svg`;
    const data = readFileSync(file, 'utf-8').trim().replace('<svg ', `<svg fill="${color}" `);
    return `url("data:image/svg+xml,${encodeURIComponent(data).replace(/'/g, '%27')}")`;
};

// Codebase icon font classes (`.icon-<key>:before`) -> Octicon.
const fontIcons = {
    'assignee_id': 'person',
    'attachment': 'paperclip',
    'branch': 'git-branch',
    'calendar': 'calendar',
    'category_id': 'apps',
    'commit': 'git-commit',
    'copy': 'copy',
    'copy-link': 'link',
    'edit': 'pencil',
    'milestone': 'milestone',
    'property': 'sliders',
    'related-ticket': 'cross-reference',
    'remove': 'x',
    'sprint': 'iterations',
    'status_id': 'issue-opened',
    'subscribe': 'bell',
    'unsubscribe': 'bell-slash',
    'tags': 'tag',
    'ticket_type_id': 'tasklist',
    'user': 'person',
    'watcher': 'eye',
    'time': 'clock',
    'add': 'plus',
    'disk': 'database',
    'users': 'people',
    'activity': 'pulse',
    'overview': 'home',
    'ticket': 'issue-opened',
    'ticket-closed': 'issue-closed',
    'download': 'download',
    'kanban': 'project',
};

// Header buttons, by their `data-tooltip` attribute.
const headerIcons = {
    'Projects': 'repo',
    'Settings': 'gear',
    'Billing': 'credit-card',
    'Search': 'search',
    'Notifications': 'bell',
};

// Page buttons (`.page-button__icon.<key>`).
const pageButtonIcons = {
    'new': 'plus',
    'tickets': 'plus',
    'back': 'arrow-left',
    'time': 'clock',
    'upload': 'upload',
    'tick': 'check',
    'edit': 'pencil',
    'add-multiple': 'plus-circle',
};

// Each icon is defined once, as a custom property used by the shared mask rule.
const mask = (name) => `    --icon: ${svg(name)};\n`;
const maskRule = `    -webkit-mask: var(--icon) center / contain no-repeat;\n    mask: var(--icon) center / contain no-repeat;\n`;

let css = `/* Generated by scripts/generate-icons.mjs, do not edit by hand. */\n\n`;

css += `/* Icon font replacements ------------------------------------------------ */\n\n`;
css += Object.keys(fontIcons).map((k) => `body .icon-${k}:not(.ThreadChanges__event):before`).join(',\n') + ` {
    content: "";
    display: inline-block;
    width: 16px;
    height: 16px;
    font-size: 0;
    line-height: 0;
    vertical-align: -3px;
    background-color: currentColor;
${maskRule}}\n\n`;
for (const [key, icon] of Object.entries(fontIcons)) {
    css += `body .icon-${key}:not(.ThreadChanges__event):before {\n${mask(icon)}}\n\n`;
}

css += `/* Timeline events: keep Codebase's box, paint the icon inside it ---------- */\n\n`;
css += `body .ThreadChanges__event[class*="icon-"]:before {
    content: "";
    border-radius: 50%;
    background-color: var(--cb-canvas-subtle);
    background-position: center;
    background-size: 16px 16px;
    background-repeat: no-repeat;
}\n\n`;
for (const [key, icon] of Object.entries(fontIcons)) {
    css += `body .ThreadChanges__event.icon-${key}:before {\n    background-image: ${svgColor(icon, '#59636e')};\n}\n\n`;
}

css += `/* Header buttons ------------------------------------------------------- */\n\n`;
css += `body .site-header__button:before {
    content: "";
    width: 16px;
    height: 16px;
    background-color: #fff;
${maskRule}}\n\nbody .site-header__button-img {\n    display: none;\n}\n\n`;
for (const [tooltip, icon] of Object.entries(headerIcons)) {
    css += `body .site-header__button[data-tooltip="${tooltip}"]:before {\n${mask(icon)}}\n\n`;
}

css += `/* Page buttons --------------------------------------------------------- */\n\n`;
css += `body .page-button__icon {\n    background-image: none !important;\n    padding-left: 0 !important;\n    min-height: 0;\n}\n\n`;
css += `body .page-button__icon:before {
    content: "";
    display: inline-block;
    width: 16px;
    height: 16px;
    margin-right: 6px;
    vertical-align: -3px;
    background-color: currentColor;
${maskRule}}\n\n`;
for (const [key, icon] of Object.entries(pageButtonIcons)) {
    css += `body .page-button__icon.${key}:before {\n${mask(icon)}}\n\n`;
}

css += `/* Activity feed preferences ---------------------------------------------- */\n\n`;
css += `body .preference-link__inner {
    background-image: none !important;
    margin-left: 0;
    padding-left: 0;
}\n\n`;
css += `body .preference-link__inner:before {
    content: "";
    display: inline-block;
    width: 14px;
    height: 14px;
    margin-right: 6px;
    vertical-align: -2px;
    background-color: currentColor;
${maskRule}${mask('rss')}}\n\n`;
css += `body .preference-link--group .preference-link__inner:before {\n${mask('list-unordered')}}\n\n`;

css += `/* Ticket list quick search --------------------------------------------- */\n\n`;
css += `body #content .quick-search input.query {\n    background-image: ${svgColor('search', '#59636e')};\n}\n\n`;

writeFileSync('src/styles/Icons.css', css.trimEnd() + '\n');
console.log('Wrote src/styles/Icons.css');
